# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_tags.ui'
#
# Created: Wed Nov 05 16:52:35 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_add_tags_dialog(QtGui.QMainWindow):
    def setupUi(self, add_tags_dialog):
        add_tags_dialog.setObjectName(_fromUtf8("add_tags_dialog"))
        add_tags_dialog.resize(372, 447)
        self.lineEdit = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit.setGeometry(QtCore.QRect(190, 80, 150, 20))
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 120, 150, 20))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 160, 150, 20))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 200, 150, 20))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.tag_genre = QtGui.QLabel(add_tags_dialog)
        self.tag_genre.setGeometry(QtCore.QRect(50, 120, 150, 25))
        self.tag_genre.setMinimumSize(QtCore.QSize(150, 25))
        self.tag_genre.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.tag_genre.setFont(font)
        self.tag_genre.setObjectName(_fromUtf8("tag_genre"))
        self.label_song_title = QtGui.QLabel(add_tags_dialog)
        self.label_song_title.setGeometry(QtCore.QRect(50, 80, 150, 25))
        self.label_song_title.setMinimumSize(QtCore.QSize(150, 25))
        self.label_song_title.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.label_song_title.setFont(font)
        self.label_song_title.setObjectName(_fromUtf8("label_song_title"))
        self.label_artist = QtGui.QLabel(add_tags_dialog)
        self.label_artist.setGeometry(QtCore.QRect(50, 160, 150, 25))
        self.label_artist.setMinimumSize(QtCore.QSize(150, 25))
        self.label_artist.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.label_artist.setFont(font)
        self.label_artist.setObjectName(_fromUtf8("label_artist"))
        self.label_album = QtGui.QLabel(add_tags_dialog)
        self.label_album.setGeometry(QtCore.QRect(50, 200, 150, 25))
        self.label_album.setMinimumSize(QtCore.QSize(150, 25))
        self.label_album.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.label_album.setFont(font)
        self.label_album.setObjectName(_fromUtf8("label_album"))
        self.label_bpm = QtGui.QLabel(add_tags_dialog)
        self.label_bpm.setGeometry(QtCore.QRect(50, 280, 150, 25))
        self.label_bpm.setMinimumSize(QtCore.QSize(150, 25))
        self.label_bpm.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.label_bpm.setFont(font)
        self.label_bpm.setObjectName(_fromUtf8("label_bpm"))
        self.label_year = QtGui.QLabel(add_tags_dialog)
        self.label_year.setGeometry(QtCore.QRect(50, 240, 150, 25))
        self.label_year.setMinimumSize(QtCore.QSize(150, 25))
        self.label_year.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.label_year.setFont(font)
        self.label_year.setObjectName(_fromUtf8("label_year"))
        self.label_key = QtGui.QLabel(add_tags_dialog)
        self.label_key.setGeometry(QtCore.QRect(50, 320, 150, 25))
        self.label_key.setMinimumSize(QtCore.QSize(150, 25))
        self.label_key.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.label_key.setFont(font)
        self.label_key.setObjectName(_fromUtf8("label_key"))
        self.label_info = QtGui.QLabel(add_tags_dialog)
        self.label_info.setGeometry(QtCore.QRect(50, 360, 150, 25))
        self.label_info.setMinimumSize(QtCore.QSize(150, 25))
        self.label_info.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.label_info.setFont(font)
        self.label_info.setObjectName(_fromUtf8("label_info"))
        self.lineEdit_5 = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 280, 150, 20))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 320, 150, 20))
        self.lineEdit_6.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 360, 150, 20))
        self.lineEdit_7.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(add_tags_dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 240, 150, 20))
        self.lineEdit_8.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(11)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label = QtGui.QLabel(add_tags_dialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.button_cancel = QtGui.QPushButton(add_tags_dialog)
        self.button_cancel.setGeometry(QtCore.QRect(270, 400, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(10)
        self.button_cancel.setFont(font)
        self.button_cancel.setObjectName(_fromUtf8("button_cancel"))
        self.button_save = QtGui.QPushButton(add_tags_dialog)
        self.button_save.setGeometry(QtCore.QRect(180, 400, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(10)
        self.button_save.setFont(font)
        self.button_save.setObjectName(_fromUtf8("button_save"))

        self.retranslateUi(add_tags_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_tags_dialog)

    def retranslateUi(self, add_tags_dialog):
        add_tags_dialog.setWindowTitle(_translate("add_tags_dialog", "Add tags", None))
        self.tag_genre.setText(_translate("add_tags_dialog", "Genre", None))
        self.label_song_title.setText(_translate("add_tags_dialog", "Title", None))
        self.label_artist.setText(_translate("add_tags_dialog", "Artist", None))
        self.label_album.setText(_translate("add_tags_dialog", "Album", None))
        self.label_bpm.setText(_translate("add_tags_dialog", "Beats per minute", None))
        self.label_year.setText(_translate("add_tags_dialog", "Year", None))
        self.label_key.setText(_translate("add_tags_dialog", "Key", None))
        self.label_info.setText(_translate("add_tags_dialog", "Info", None))
        self.label.setText(_translate("add_tags_dialog", "Add custom tags", None))
        self.button_cancel.setText(_translate("add_tags_dialog", "Cancel", None))
        self.button_save.setText(_translate("add_tags_dialog", "Save", None))

